//
//  MVVM ViewModel
//  ___FILENAME___ at ___PROJECTNAME___
//
//  MVVM ViewModel Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sandor Ferreira
//

protocol ___FILEBASENAME___ViewModel {
    // protocol variables and functions
}

class ___FILEBASENAME___ViewModel {
    // variables
    
    // functions
}
