//
//  MVVM ViewController
//  ___FILENAME___ at ___PROJECTNAME___
//
//  MVVM ViewController Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sandor Ferreira
//

import UIKit

class ___FILEBASENAME___ViewController: UIViewController {
    
    var viewModel: ___FILEBASENAME___ViewModel?
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}
