//
//  MVVM Model
//  ___FILENAME___ at ___PROJECTNAME___
//
//  MVVM Model Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sandor Ferreira
//

struct ___FILEBASENAME___Model: Codable {

}
